    name: Scheduled Hello World

    on:
      schedule:
        # Runs every 5 minutes
        - cron: '*/5 * * * *' 

    jobs:
      hello-world-job:
        runs-on: ubuntu-latest
        steps:
          - name: Say Hello
            run: echo "Hello, World! This is a scheduled GitHub Action."
