    name: Scheduled Hello World

    on:
        workflow_dispatch:
                # Optional: Define inputs if the workflow requires user input
                inputs:
                  logLevel:
                    description: 'Log level'
                    required: true
                    default: 'warning'
                  tags:
                    description: 'Reason for running workflow'
                    required: true
                    type: string
                
    jobs:
      hello-world-job:
        runs-on: ubuntu-latest
        steps:
          - name: Say Hello
            run: echo "Hello, World! This is a scheduled GitHub Action."
